### ISSUE TITLE
cannot create service block with no selected service

### ISSUE THREAD

**Issue by hamidzr** [NetsBlox/NetsBlox#1675]
recreate:
1. create a service block
2. unset the service
3. duplicate the block

**Comment by brollb** [comment]
This no longer prevents the duplication of the block but it does display a message saying `Service "" is not available`. This is due to gracefully handling unsupported services (https://github.com/NetsBlox/Snap--Build-Your-Own-Blocks/issues/822, https://github.com/NetsBlox/Snap--Build-Your-Own-Blocks/pull/824, https://github.com/NetsBlox/Snap--Build-Your-Own-Blocks/pull/825, https://github.com/NetsBlox/Snap--Build-Your-Own-Blocks/pull/827)

**Comment by hamidzr** [comment]
it does not. great!
