### ISSUE TITLE
translation service name #742

### ISSUE THREAD

**Issue by hamidzr** [NetsBlox/NetsBlox#2257]
should the name reflect the backend provider? as we do with some other ones like google maps? But you could argue that the interface for a translation service is less backend dependent than a map service and multiple backends could work under one service..

As far as attribution goes we are doing that through the help docs.

**Comment by gsteinLTU** [comment]
We had a little discussion about this before as part of allow/block lists (more specifically making drop-in replacements for Google services for regions where they aren't allowed). The end user doesn't really care or need to know (unless the license requires it) where a service is supplied from, just what it does. I don't think we moved forwards with it in any way, but I remember talking about having some sort of setting to choose between which "Maps"/"Translation"/etc service is used for that name.

**Comment by brollb** [comment]
The initial services actually were given generic names rather than naming them based on the backend provider but then were updated to conform to a single convention (upper camel-case and using backend provider names). However, there are a few benefits to naming them based on the provider.

I think it is beneficial to provide transparency to the students. It is more clear to the students that they are interacting with familiar names. This can be seen in the feedback from the fifth grader science classroom last year -  some students mentioned that they really enjoyed "controlling Google." Although, they that's not how I would describe using an API from a company (I still find it rather amusing), it does seem that knowing the backend provider made using the given service more relevant and interesting to the students.

Along with making the services more relevant to the students, I think it is also highlights the fact that NetsBlox is integrating with existing data sources. This will be more important when looking at using NetsBlox with science curriculum, etc. This can also make generic names a little trickier to come up with (especially if we are providing similar but not identical services). Expressing nuances between services in the name alone can be challenging; if we are using the provider's name, then learning the nuances between the different providers can be delegated to the users to an extent and provided in the help messages. Regardless, the distinction between similar services will be clear and easy to understand (backed by different APIs) and the nuances can be investigated as needed from there.

Another benefit is naming consistency. We could provide generic names and only provide info about the backend provider when the license requires it but this could introduce inconsistencies if we named most with generic names and then specific names for a few exceptions.

Naming the services based off of the provider also keeps options open in the future for allowing users to associate personal API keys to their account for use with specific services (if there are any scale issues and we want to allow custom API key usage). This is much cleaner to do if the services are transparent about the backend service. 

Also, IEXTrading was initially called Stocks when it was first being created but we changed it to conform to the convention before merging it into master.

Wow, this comment really ended up much longer than intended!

**Comment by gsteinLTU** [comment]
Maybe we need a rule about having TL;DRs if comments go too long.

**Comment by hamidzr** [comment]
Thanks for the detailed comment. having a generic name has the benefit of being able to provide different backends especially in this case since I assume translation providers APIs are going to be very similar thus allowing us to easily merge them together, for example with offline translators. This approach would be a little easier on the user as they can just use one service.
But one could also argue that maybe being aware of these limitations is a talking point for teaching some of those concepts. 
I discussed some of these concerns in one of our meetings and considering the service names are already inconsistent and with our current setup, we can easily provide backward compatibility for changing service names we published the service as is.
