### ISSUE TITLE
KeyValueStore demonstrates strange behavior

### ISSUE THREAD

**Issue by CliffordAnderson** [NetsBlox/NetsBlox#2272]
Hi @brollb,

I may be missing how the KeyValueStore is supposed to work, but I wanted to call attention to what seems like strange behavior. Currently, the RPC is not allowing me to set the value of keys:

![screen shot 2018-11-14 at 9 46 50 pm](https://user-images.githubusercontent.com/1919466/48529083-2c6deb00-e857-11e8-9530-f4f4dfae089e.png)
![screen shot 2018-11-14 at 9 46 59 pm](https://user-images.githubusercontent.com/1919466/48529088-309a0880-e857-11e8-9f76-9bd646f1c4df.png)

I also notice that integer keys build a list, which I can edit but cannot seem to delete:

![screen shot 2018-11-14 at 9 47 57 pm](https://user-images.githubusercontent.com/1919466/48529113-56bfa880-e857-11e8-9db3-46ca1f1613eb.png)

Any tips on how to solve these issues? Or am I missing the point of the RPC?

**Comment by brollb** [comment]
Strange. I will check it out and see if I can figure out what is going on (in the first two pictures, it looks like you are using it correctly). In the third picture, I believe it is actually printing all the top level keys - though I am not sure why there are so many with empty keys.

Is there a reason why you are using the KeyValueStore instead of the CloudVariables service? I generally recommend using the CloudVariables service over the KeyValueStore. It supports some nice features like locking variables to address any race conditions as well as basic access control so you can prevent other users from editing your variables (as well as user specific variables which cannot be overwritten by other variables).

In most ways, CloudVariables is an updated version of KeyValueStore (which was one of the earliest services). The only unsupported feature of the KeyValueStore service in the CloudVariables is support for hierarchical storage. This would've added unnecessary complexity when combined with the access control and locking capabilities added in CloudVariables (and more important concepts imo).

**Comment by CliffordAnderson** [comment]
Thanks for the quick response. I think I accidentally generated the list of integer keys by using `1` and then `100` as tests. The block seems to have created all the empty keys in between.

Good advice about sticking with CloudVariables. I was thinking about teaching both tomorrow, precisely because I liked the hierarchical storage (parent/child) of the KeyValueStore. But it's really no problem to stick with CloudVariables to share the basics of how a key/value store works and, as you suggest, I hope to talk about race conditions and locks. 

Again, appreciate the help!

**Comment by hamidzr** [comment]
looks like there is an issue with the `put` RPC in the running version of the service. I'm not getting the same behavior on my local setup. could it be a versioning issue..

**Comment by hamidzr** [comment]
in the backend the values for this keyValue service are stored in a disngle mongo document which is supposed to be structure like this:
```
{ 
    "_id" : "KeyValueStore", 
    "value" : {
        "1" : "ss", 
        "20" : "65", 
        "asdf" : "ss", 
        "undefined" : "ss", 
        " " : "ss", 
        "dds" : "ss"
    }
}
```

but now it's looking like
```
{ 
    "_id" : "KeyValueStore", 
    "value" : [
        "test", 
        null, 
        null
    ]
}
```

**Comment by CliffordAnderson** [comment]
Yes, that scenario definitely makes sense. But I'm still having problems putting and getting new variables. I just tried to put a key `schluessel` with a value of `1`. The put returned `Ok` but when I tried to get the value I still received `false`.

**Comment by hamidzr** [comment]
That's because the corrupted values were not flushed out yet. It should
behave now. It's however, still vulnerable to the original issue as we
haven't pushed a fix yet.

**Comment by CliffordAnderson** [comment]
Got it! Thanks.

**Comment by hamidzr** [comment]
> it will fail since c is technically the equivalent of a directory and contains subkeys rather than simply a primitive value. 
@brollb it is not failing in my case. it overrides the "directory" with a primitive value which is imo expected.
However, when you try to do the reverse, set `a/b/c` to value then try to set `a/b/c/d` to another value it will return false.

**Comment by brollb** [comment]
There have been a few updates on this front (merged into master but not part of a release yet): #2707 #2704 #2706 #2705 

The biggest takeaway is that a key can now be used as a directory and have a value (as well as have a password). In other words, you can set some key, like `a`, to a value and then set `a/b` to another value. Calling `child(a)` will give `['a/b']` and `get(a)` will return the value stored under `a`.
