### ISSUE TITLE
pong example slow

### ISSUE THREAD

**Issue by hamidzr** [NetsBlox/NetsBlox#2296]
pong example is slow after introducing a small delay to `send message`

**Comment by DarDoro** [comment]
Sorry for necroposting but this Issue is still open.
I'm afraid it's caused by refresh policy.
This snippet took 1 s to complete.
![myRole script pic](https://user-images.githubusercontent.com/16109071/82580631-a9d29400-9b8f-11ea-9911-996143396af3.png)
And this one ... 2s.
![myRole script pic (1)](https://user-images.githubusercontent.com/16109071/82580747-e0a8aa00-9b8f-11ea-8e11-56a648f5972b.png)

**Comment by brollb** [comment]
@DarDoro - No worries about the necropost :) 

Although this might be a bit surprising, I believe this is actually the expected behavior inherited from Snap!. Both Snap! and NetsBlox have an artificial slowdown applied to the blocks which can be disabled by switching to "Turbo" mode (shift clicking the green flag will turn it into a green flag which enables turbo mode). I believe part of the motivation was to ensure programs behaved the same on different computers and that students would be able to see more of the programs execution rather than having everything happen almost instantaneously.

**More details about execution of scripts in Snap!/NetsBlox**
Program execution is actually handled by a single process which is shared among all blocks and concurrent scripts. Concurrent scripts are executed by each running until they "yield" control of the process. Once the script yields control of the process, the next execution script can run (until it, in turn, yields). The VM running these scripts will let each running script run until it yields as one "step". The artificial slowdown of the block execution (ie, the VM) is performed by essentially stepping the VM less frequently. I recently wrote a [blog post](http://brollb.github.io/general/netsblox/2020/05/15/race-conditions-in-netsblox/) about race conditions that touches on this a little bit. 

Anyway, we can use this to explain the behavior in the above scripts. In the first example, the loop is doing nothing 60 times. However, loops actually yield at the end and each script will only run-until-yield once every time the VM steps. Since the VM has an artificial delay, this means that it will accumulate time for each iteration of the repeat loop. That is, it will yield 60 times resulting in an overall execution time of 1 second (VM appears to step once every 1/60th of a second). If you switch to turbo mode, the value of `timer` will be 0 as the VM will be stepping much more frequently.

Looking at the next script, we have added a `wait` block. The `wait` block also will result in a yield. As a result the new script will yield 120 times and will accumulate twice as much time as the previous script (ie, 2 seconds). If you enable turbo mode, the value of `timer` will again be 0.

Hopefully that makes sense! :)

**Comment by brollb** [comment]
This might also be of interest: https://github.com/NetsBlox/Snap--Build-Your-Own-Blocks/blob/master/threads.js#L2058-L2059

**Comment by DarDoro** [comment]
Yes it's Snap! heritage., World.oneCycle() is synchronized with the screen refresh rate by requestAnimationFrame(). And oneCycle() returns after every loop iteration, custom block, conditional and every possible (or not ;) opportunity. Maybe this aggressive 
 cooperative scheduling is beneficial for network operation but rendering of graphics is perceived slow in normal mode or jerky in turbo at 2 FPS.

The cause of this issue is quite clear, so it can be closed, isn't it?
