### ISSUE TITLE
Failing to build docs for NYT Service (suspected bug in the service)

### ISSUE THREAD

**Issue by brollb** [NetsBlox/NetsBlox#3186]
```
Error: failed to compile docs: error: , stderr: /home/brian/projektek/netsblox/src/server/docs/_generated/services/NewYorkTimes/Concepts.rst:15: WARNING: duplicate function description of NewYorkTimes.getArticlesWithConcept, other function in services/NewYorkTimes/Articles
, stdout: Running Sphinx v4.0.2
making output directory... done

```

**Comment by brollb** [comment]
Actually, this appears to be a result of the RPC being part of two categories:
```javascript
/**
 * Fetch up to 10 articles containing the given concept.
 *
 * @category Concepts
 * @category Articles
 * @param{Object} concept
 * @param{String} concept.name
 * @param{ConceptType} concept.type
 * @returns{Array<Article>}
 */
```

@dragazo - would you mind checking this out?

**Comment by brollb** [comment]
It looks like the documentation is still being generated fine but it might be nice not to have the warning.

**Comment by dragazo** [comment]
Yeah, I was thinking that could happen if we ever had one in multiple categories. Services in multiple categories should be fine since they're just dynamically generated links, but sphinx is picky about function declarations. There's probably a setting to just disable that type of warning; I'll look into it.
