### ISSUE TITLE
Projects with Illegal Characters

### ISSUE THREAD

**Issue by plaforet** [NetsBlox/NetsBlox#3259]
Good morning,

While Netsblox doesn't allow you to save a project with a period in it, It seems you _can_ save a project with a slash or question mark. When you try to share a project with either of these characters, or if you try to delete the project Netsblox crashes. I made a short video to demonstrate: [https://youtu.be/I0fvU5vSDmI](https://youtu.be/I0fvU5vSDmI)

I can't seem to duplicate this error in Snap, if that helps.

**Comment by brollb** [comment]
Thanks for the heads up! We will check it out and post updates here!

**Comment by plaforet** [comment]
Excellent, let me know if there's anything I can do to help. I tried finding where you're handling the error for project names that include periods, so I could try my hand at resolving this issue, but I haven't worked with a project of this magnitude and didn't know where to look. I'm but a lowly CS teacher lol

**Comment by brollb** [comment]
I saw your response already after I had a fix for this. (Darn - it would've been a good issue to start with!) I was hoping I could revert my fix so you could take the issue but it looks like GitHub's notification didn't disappear even after removing it from the project's history. Bummer.

Anyway, if you are interested in contributing, I have labeled [some issues](https://github.com/NetsBlox/NetsBlox/labels/good%20first%20issue) with the "good first issue" label. Generally, adding new (native) services is a good place to start (and appreciated!) since they are relatively independent of the rest of the code. [Here is some documentation](https://dev.netsblox.org/docs/dev/services-overview.html#how-can-i-contribute-a-native-service) to get started.

That said, if you have your own an idea for an interesting new service, that would be great, too! Just open an issue to let us know you are working on it and we can answer any questions you might have about getting started! (A couple data sources that I find interesting are [data.gov](https://www.data.gov/) and [UNdata](https://data.un.org/).)
