### ISSUE TITLE
Documentation for community services

### ISSUE THREAD

**Issue by brollb** [NetsBlox/NetsBlox#3414]
The URL in the help message for community services is incorrect and should be either fixed or removed.

![DeepinScreenshot_select-area_20220510152144](https://user-images.githubusercontent.com/4982789/167715300-f425025b-e877-4aa1-b362-6c8d7c4938a5.png)

**Comment by brollb** [comment]
@dragazo

**Comment by dragazo** [comment]
@brollb Ok, I have this fixed in [browser PR 1302](https://github.com/NetsBlox/Snap--Build-Your-Own-Blocks/pull/1302). It just hides the link for non-FS services. I figure we probably don't want to host arbitrary docs like community services since they could be low quality and have to be moderated for inappropriate content.
