### ISSUE TITLE
Block Request: Async JavaScript Function

### ISSUE THREAD

**Issue by sofabeddd** [NetsBlox/NetsBlox#3452]
similar to the javascript function block, could we get an asynchronous function block along side it? returning values of promises is impossible without it

**Comment by brollb** [comment]
This is a little tricky but still possible with the current JS block. There are some async examples in the custom library blocks (like "costume from url v2"). I would do something like this (explanation after the code snippet):
```javascript
if (!proc.asyncTaskState) {  // If it is the first time the function is called, call the async task and initialize the state object
  const promise = someAsyncFn()
    .catch(err => proc.asyncTaskState && proc.asyncTaskState.error = err)
    .then(result => proc.asyncTaskState && proc.asyncTaskState.result = result);
  proc.asyncTaskState = {};
} else if (proc.asyncTaskState.hasOwnProperty('result')) {  // If it completed successfully, retrieve the result & reset the state
  const {result} = proc.asyncTaskState;
  delete proc.asyncTaskState;
  return result;
} else if (proc.asyncTaskState.hasOwnProperty('error')) {  // If it errored, throw the error & reset the state
  const {error} = proc.asyncTaskState;
  delete proc.asyncTaskState;
  throw error;
}
proc.pushContext('doYield');  // yield to another set of scripts. (This function will be called again!)
proc.pushContext();
```

So, `proc` should be one more argument than is provided to the JS function block. An example is shown below. Basically, when you have an async task in a JS block, you can use the bottom two statements (specifying that it needs to yield and push an empty context) to have the block continue to be called - in other words, it will not proceed to the next block yet. This is exactly what we need in async tasks since the block doesn't have anything to return until the async function completes (and the promise is resolved). Here is the example of the `costume from url v2` block:
![myRole script pic (58)](https://user-images.githubusercontent.com/4982789/192328436-d52b0b75-6348-44ff-8b67-67dad12471e9.png)

**Comment by brollb** [comment]
Did this help or are there still issues/questions?

**Comment by brollb** [comment]
@sofabeddd - I am going to close this for now since the above solution should fix your problem. If you have any other issues, feel free to re-open or create a new issue!
