### ISSUE TITLE
Snap behind commit

### ISSUE THREAD

**Issue by 18001767679** [NetsBlox/NetsBlox#3468]
I couldn't find those hyperblocks or smth like that!

**Comment by brollb** [comment]
Hello!

Although the NetsBlox client trails the Snap version (since it takes some time to integrate their changes), hyperblocks have been integrated. Hyperblocks actually just added support for accepting list inputs to the existing blocks (like addition, multiplication, etc) and run much faster than using a loop or map.

**Comment by brollb** [comment]
Closing this but feel free to respond if you have more questions!
